export const DailyNeedsData = [
  {
    _id: "653245698563246",
    name: "Groceries",
    img: require("../../assets/images/groceries.png"),
    href: "#",
  },
  {
    _id: "698456358965478",
    name: "Meat",
    img: require("../../assets/images/meat.jpg"),
    href: "#",
  },
  {
    _id: "674569812365415",
    name: "Vegetables & Fruits",
    img: require("../../assets/images/vegetables.jpg"),
    href: "#",
  },
  {
    _id: "632145698745265",
    name: "Dairy Products",
    img: require("../../assets/images/dairyproducts.png"),
    href: "#",
  },
  {
    _id: "632548125462987",
    name: "Prasadalu",
    img: require("../../assets/images/prasadam.jpg"),
    href: "#",
  },
  {
    _id: "614789587632541",
    name: "Home Foods",
    img: require("../../assets/images/homefoods.jpg"),
    href: "#",
  },
];

export const GroceriesData = [
  {
    _id: "632152698475696",
    name: "Rice & Rice Products",
    img: require("../../assets/images/riceProducts.png"),
    href: "#",
  },
  {
    _id: "852645975632541",
    name: "Flours",
    img: require("../../assets/images/LooseRice.png"),
    href: "#",
  },
  {
    _id: "745632156945635",
    name: "Masala and Spices",
    img: require("../../assets/images/MasalaProducts.png"),
    href: "#",
  },
  {
    _id: "654123852741963",
    name: "Cooking Ingredients",
    img: require("../../assets/images/CookingIngredientsProducts.jpg"),
    href: "#",
  },
];

export const RiceProductsData = [
  {
    _id: "6456326489",
    name: "Fortune Rice",
    img: require("../../assets/images/FortuneRice.png"),
    price: 1340,
    discount: "0",
    discountType: "Rupees",
    rating: "4.8",
    unit: "25 Kg",
    about:
      "Fortune’s most premium long-grain basmati rice has been sourced from the richest Himalayan foothills. Each grain has been traditionally aged for a vintage touch that ensures that your Biriyani is a class apart. This long-grain basmati rice encapsulates a perfect combination of aroma and taste that is so magnificent that it makes each occasion one of opulence. So, go ahead and get your own premium biryani basmati rice online!",
  },
  {
    _id: "4563264896",
    name: "India Gate Rice",
    img: require("../../assets/images/IndiaGateRice.png"),
    price: 530,
    discount: "0",
    discountType: "Rupees",
    rating: "4.8",
    unit: "5 Kg",
    about:
      "India Gate Mogra Basmati Rice is inexpensive for everyday usage and adds flavour to simple recipes. It is identified by the distinctive Basmati aroma and texture, as well as the broken Basmati grains. This distinctively aromatic and savoury variety will cater to your preference and make each meal special for people who seek a cost-effective product for everyday usage. Despite being broken, the grains grow up to two times longer when cooked. This Mogra Basmati rice is raised and harvested in the northwest foothills of the Himalayas. It is perfectly aged which improves volume, fluffiness, and yield. Additionally, this ageing process gives Basmati its distinctive flavour and aroma",
  },
  {
    _id: "7456325693",
    name: "Jasmine Rice",
    img: require("../../assets/images/JasmineRice.png"),
    price: 56,
    discount: "0",
    discountType: "Rupees",
    rating: "4.8",
    unit: "Kg",
    about:
      "Thai jasmine rice and Cambodian rice share many of the same characteristics and grow mainly in neighboring geographic areas on opposite sides of the northeastern Thai-Cambodian border. Cambodian jasmine rice is cultivated in Cambodia and processed as white (milled and polished) and brown rice. Distinct Cambodian jasmine rice varieties include these three, phka rumduol, phka romeat, and phka rumdeng. Recent DNA fingerprint analysis, carried out with 18 markers, shows that all three varieties possess 18 known fragrance alleles. Two varietals (phka rumduol and phka rumdeng) are distinctly Cambodian with 17 markers in identical positions, with Thai jasmine rice and one fragrance marker each in a different position.[citation needed] The analysis of Cambodian phka romeat shows all 18 markers in identical positions with the trademarked Thai jasmine rice Thai hom mali.",
  },
  {
    _id: "5632148963",
    name: "Loose Rice",
    img: require("../../assets/images/LooseRice.png"),
    price: 50,
    discount: "0",
    discountType: "Rupees",
    rating: "4.8",
    unit: "Kg",
    about:
      "Raw rice contains less starch and is easily digestible.The rice is lightweight and has a distinct aroma.Ideal for preparing dishes like sweet pongal, biryani, fried rice etcSona masoori is a super fine grain",
  },
];

export const FloursData = [
  {
    _id: "6456326489",
    name: "Loose Flour",
    img: require("../../assets/images/maida.jpg"),
    price: 34,
    discount: "0",
    discountType: "Rupees",
    rating: "4.8",
    unit: "Kg",
  },
  {
    _id: "4563264896",
    name: "Maida",
    img: require("../../assets/images/maida.jpg"),
    price: 30,
    discount: "0",
    discountType: "Rupees",
    rating: "4.8",
    unit: "Kg",
  },
];

export const MasalaAndSpicesData = [
  {
    _id: "6456326489",
    name: "Aachi Mutton Masala",
    img: require("../../assets/images/aachimattonmasala.jpg"),
    price: 60,
    discount: "0",
    discountType: "Rupees",
    rating: "4.8",
    unit: "Packet",
  },
  {
    _id: "4563264896",
    name: "Everest Cumin Powder",
    img: require("../../assets/images/aachimattonmasala.jpg"),
    price: 50,
    discount: "0",
    discountType: "Rupees",
    rating: "4.8",
    unit: "Packet",
  },
  {
    _id: "4563264896",
    name: "Hyderabadi Biryani Mix",
    img: require("../../assets/images/aachimattonmasala.jpg"),
    price: 55,
    discount: "0",
    discountType: "Rupees",
    rating: "4.8",
    unit: "Packet",
  },
  {
    _id: "4563264896",
    name: "Biryani Masala",
    img: require("../../assets/images/aachimattonmasala.jpg"),
    price: 40,
    discount: "0",
    discountType: "Rupees",
    rating: "4.8",
    unit: "Packet",
  },
];

export const CookingIngredientsData = [
  {
    _id: "6456326489",
    name: "All varieties of Dals",
    img: require("../../assets/images/MasalaProducts.png"),
    price: 34,
    discount: "0",
    discountType: "Rupees",
    rating: "4.8",
    unit: ["100 gm", "250 gm", "500 gm", "750 gm", "kg"],
  },
  {
    _id: "4563264896",
    name: "Millets",
    img: require("../../assets/images/MasalaProducts.png"),
    price: 30,
    discount: "0",
    discountType: "Rupees",
    rating: "4.8",
    unit: ["100 gm", "250 gm", "500 gm", "750 gm", "Kg"],
  },
];

export const SpicyRestaurantData = [
  {
    _id: "632152698475696",
    name: "Biryani",
    img: require("../../assets/images/biryani32.png"),
    href: "#",
  },
  {
    _id: "852645975632541",
    name: "Non-Veg Curries",
    img: require("../../assets/images/biryani32.png"),
    href: "#",
  },
  {
    _id: "745632156945635",
    name: "Veg Curries",
    img: require("../../assets/images/biryani32.png"),
    href: "#",
  },
  {
    _id: "654123852741963",
    name: "Naans and Rotis",
    img: require("../../assets/images/biryani32.png"),
    href: "#",
  },
];

export const BiryaniData = [
  {
    _id: "6456326489",
    name: "Veg Biryani",
    img: require("../../assets/images/biryani32.png"),
    price: 240,
    discount: "0",
    discountType: "Rupees",
    rating: "4.8",
    unit: "Plate",
    about:
      "Veg Biryani recipe with pot, pressure cooker & Instant pot options. Vegetable Biryani is an aromatic rice dish made with basmati rice, mix veggies, herbs & biryani spices. This easy Veg Biryani is a total crowd pleaser! You will love this for everything from busy night meals to holiday family dinners. Biryani is a celebration of exotic flavors, vibrant colors and pleasing aromas infused into a pot of goodness. So this vegetarian dish is a perfect & hearty dinner packed with fragrant rice, vegetables, crunchy nuts, aromatic spices and herbs. It’s a dish you will often turn to time and again!",
  },
  {
    _id: "4563264896",
    name: "Egg Biryani",
    img: require("../../assets/images/biryani32.png"),
    price: 300,
    discount: "0",
    discountType: "Rupees",
    rating: "4.8",
    unit: "Plate",
    about:
      "Veg Biryani recipe with pot, pressure cooker & Instant pot options. Vegetable Biryani is an aromatic rice dish made with basmati rice, mix veggies, herbs & biryani spices. This easy Veg Biryani is a total crowd pleaser! You will love this for everything from busy night meals to holiday family dinners. Biryani is a celebration of exotic flavors, vibrant colors and pleasing aromas infused into a pot of goodness. So this vegetarian dish is a perfect & hearty dinner packed with fragrant rice, vegetables, crunchy nuts, aromatic spices and herbs. It’s a dish you will often turn to time and again!",
  },
  {
    _id: "7456325693",
    name: "Special Chicken Biryani",
    img: require("../../assets/images/biryani32.png"),
    price: 350,
    discount: "0",
    discountType: "Rupees",
    rating: "4.8",
    unit: "Kg",
    about:
      "Veg Biryani recipe with pot, pressure cooker & Instant pot options. Vegetable Biryani is an aromatic rice dish made with basmati rice, mix veggies, herbs & biryani spices. This easy Veg Biryani is a total crowd pleaser! You will love this for everything from busy night meals to holiday family dinners. Biryani is a celebration of exotic flavors, vibrant colors and pleasing aromas infused into a pot of goodness. So this vegetarian dish is a perfect & hearty dinner packed with fragrant rice, vegetables, crunchy nuts, aromatic spices and herbs. It’s a dish you will often turn to time and again!",
  },
  {
    _id: "5632148963",
    name: "Fry Piece Biryani",
    img: require("../../assets/images/biryani32.png"),
    price: 320,
    discount: "0",
    discountType: "Rupees",
    rating: "4.8",
    unit: "Plate",
    about:
      "Veg Biryani recipe with pot, pressure cooker & Instant pot options. Vegetable Biryani is an aromatic rice dish made with basmati rice, mix veggies, herbs & biryani spices. This easy Veg Biryani is a total crowd pleaser! You will love this for everything from busy night meals to holiday family dinners. Biryani is a celebration of exotic flavors, vibrant colors and pleasing aromas infused into a pot of goodness. So this vegetarian dish is a perfect & hearty dinner packed with fragrant rice, vegetables, crunchy nuts, aromatic spices and herbs. It’s a dish you will often turn to time and again!",
  },
];

export const AskForServiceData = [
  {
    _id: "632152698475696",
    name: "Switch & Socket",
    img: require("../../assets/images/electrician.jpg"),
    href: "#",
  },
  {
    _id: "852645975632541",
    name: "Lights & Chandelier",
    img: require("../../assets/images/electrician.jpg"),
    href: "#",
  },
  {
    _id: "745632156945635",
    name: "Fan",
    img: require("../../assets/images/electrician.jpg"),
    href: "#",
  },
  {
    _id: "654123852741963",
    name: "MCB & Fuse",
    img: require("../../assets/images/electrician.jpg"),
    href: "#",
  },
];

export const SwitchSocketData = [
  {
    _id: "6456326489",
    name: "Switch board installation",
    img: require("../../assets/images/electrician.jpg"),
    multiImg: [
      require("../../assets/images/electrician.jpg"),
      require("../../assets/images/electrician.jpg"),
      require("../../assets/images/electrician.jpg"),
      require("../../assets/images/electrician.jpg"),
    ],
    price: 500,
    discount: "0",
    discountType: "Rupees",
    rating: "4.8",
    unit: "",
    about:
      "An electrical switchboard provides electricity to an appliance when the switch is on by redirecting electricity from the main power supply. Electrical switchboards are quite important since these help you to control the flow of electricity.",
  },
  {
    _id: "4563264896",
    name: "AC switch board installation",
    img: require("../../assets/images/electrician.jpg"),
    multiImg: [
      require("../../assets/images/electrician.jpg"),
      require("../../assets/images/electrician.jpg"),
      require("../../assets/images/electrician.jpg"),
      require("../../assets/images/electrician.jpg"),
    ],
    price: 500,
    discount: "0",
    discountType: "Rupees",
    rating: "4.8",
    unit: "",
    about:
      "An electrical switchboard provides electricity to an appliance when the switch is on by redirecting electricity from the main power supply. Electrical switchboards are quite important since these help you to control the flow of electricity.",
  },
  {
    _id: "7456325693",
    name: "Switch board repair",
    img: require("../../assets/images/electrician.jpg"),
    multiImg: [
      require("../../assets/images/electrician.jpg"),
      require("../../assets/images/electrician.jpg"),
      require("../../assets/images/electrician.jpg"),
      require("../../assets/images/electrician.jpg"),
    ],
    price: 500,
    discount: "0",
    discountType: "Rupees",
    rating: "4.8",
    unit: "",
    about:
      "An electrical switchboard provides electricity to an appliance when the switch is on by redirecting electricity from the main power supply. Electrical switchboards are quite important since these help you to control the flow of electricity.",
  },
  {
    _id: "5632148963",
    name: "Switch / Socket replacement ",
    img: require("../../assets/images/electrician.jpg"),
    multiImg: [
      require("../../assets/images/electrician.jpg"),
      require("../../assets/images/electrician.jpg"),
      require("../../assets/images/electrician.jpg"),
      require("../../assets/images/electrician.jpg"),
    ],
    price: 500,
    discount: "0",
    discountType: "Rupees",
    rating: "4.8",
    unit: "",
    about:
      "An electrical switchboard provides electricity to an appliance when the switch is on by redirecting electricity from the main power supply. Electrical switchboards are quite important since these help you to control the flow of electricity.",
  },
];

export const AdsBanners = [
  {
    img: require("../../assets/images/ad1.jpg"),
  },
  {
    img: require("../../assets/images/ad2.jpg"),
  },
  {
    img: require("../../assets/images/ad3.jpg"),
  },
];

export const DaiyNeedsCartData = [
  {
    id: "5236489652",
    img: require("../../assets/images/aachimattonmasala.jpg"),
    name: "Aachi mutton masala",
    unit: "Packet",
    actualPrice: "65",
    finalPrice: "60",
    quantity: 2,
  },
  {
    id: "6325478521",
    img: require("../../assets/images/aachimattonmasala.jpg"),
    name: "Aachi chicken masala",
    unit: "Packet",
    actualPrice: "65",
    finalPrice: "60",
    quantity: 2,
  },
  {
    id: "4896320158",
    img: require("../../assets/images/aachimattonmasala.jpg"),
    name: "Aachi sambar masala",
    unit: "Packet",
    actualPrice: "65",
    finalPrice: "60",
    quantity: 2,
  },
];

export const FoodAndBeveragesCartData = [
  {
    id: "5236489652",
    img: require("../../assets/images/biryani32.png"),
    name: "Veg Biryani",
    unit: "Plate",
    actualPrice: "250",
    finalPrice: "230",
    quantity: 1,
  },
  {
    id: "6325478521",
    img: require("../../assets/images/biryani32.png"),
    name: "Chicken Biryani",
    unit: "Plate",
    actualPrice: "280",
    finalPrice: "260",
    quantity: 2,
  },
  {
    id: "4896320158",
    img: require("../../assets/images/biryani32.png"),
    name: "Chicken Curry",
    unit: "Plate",
    actualPrice: "150",
    finalPrice: "140",
    quantity: 1,
  },
];

export const ServicesCartData = [
  {
    id: "5236489652",
    img: require("../../assets/images/electrician.jpg"),
    name: "Switch board repair",
    minCharge: "500",
    serviceCharge: "500",
    emergencyCharge: "1000",
    discount: "0",
  },
  {
    id: "6325478521",
    img: require("../../assets/images/electrician.jpg"),
    name: "Switch board installation",
    minCharge: "500",
    serviceCharge: "700",
    emergencyCharge: "1000",
    discount: "150",
  },
  {
    id: "4896320158",
    img: require("../../assets/images/electrician.jpg"),
    name: "Fan installation",
    minCharge: "500",
    serviceCharge: "700",
    emergencyCharge: "1000",
    discount: "100",
  },
];

export const DailyNeedsProductsData = [
  {
    _id: "64a2f57754ef43035365b1fe",
    name: "Fortune Rice",
    hindiName: "फॉर्च्यून चावल",
    teluguName: "ఫార్చ్యూన్ రైస్",
    img: "file-1688401271882-951656965.webp",
    type: "EGG",
    variants: "64a2be6054ef43035365a97a",
    availableStocks: "10",
    availableStockUnit: {
      _id: "64a2be6054ef43035365a97a",
      volume: "1",
      unitValue: "kg",
      status: true,
      variant: "SOLID",
      __v: 0,
    },
    tax: {
      _id: "64a2c01254ef43035365a9a5",
      name: "GST",
      percentage: "18",
      status: true,
      __v: 0,
    },
    dailyNeed: {
      _id: "64a2f47b54ef43035365b1e0",
      name: "Rice & Rice Products",
      hindiName: "चावल एवं चावल उत्पाद",
      teluguName: "బియ్యం & బియ్యం ఉత్పత్తులు",
      bannerImg: "file-1688401019061-448292434.webp",
      location: {
        type: "Point",
        coordinates: [1.3654, 1.2658],
        _id: "64a2f47b54ef43035365b1e1",
      },
      deliveryTime: "01:00",
      openTime: [
        {
          startTime: "06:00",
          closeTime: "22:00",
          _id: "64a2f47b54ef43035365b1e2",
        },
      ],
      isActive: true,
      isChildren: true,
      __v: 0,
    },
    label: "Fortune Rice",
    hindiLabel: "फॉर्च्यून चावल",
    teluguLabel: "ఫార్చ్యూన్ రైస్",
    description: "Fortune Rice",
    hindiDescription: "फॉर्च्यून चावल",
    TeluguDescription: "ఫార్చ్యూన్ రైస్",
    isActive: true,
    productPriceInfo: [
      {
        size: "1",
        productUnit: {
          _id: "64a2be6054ef43035365a97a",
          volume: "1",
          unitValue: "kg",
          status: true,
          variant: "SOLID",
          __v: 0,
        },
        productPrice: "58",
        _id: "64a2f57754ef43035365b1ff",
      },
      {
        size: "5",
        productUnit: {
          _id: "64a2be6054ef43035365a97a",
          volume: "1",
          unitValue: "kg",
          status: true,
          variant: "SOLID",
          __v: 0,
        },
        productPrice: "290",
        _id: "64a2f57754ef43035365b200",
      },
    ],
    priceType: "MRP",
    discountValue: "0",
    discountType: "RS",
    __v: 0,
  },
  {
    _id: "64a2fdb954ef43035365b3f0",
    name: "product1",
    hindiName: "product1",
    teluguName: "product1",
    img: "file-1688403385059-475969550.webp",
    type: "VEG",
    variants: "64a2fd6854ef43035365b3d8",
    availableStocks: "500",
    availableStockUnit: {
      _id: "64a2be6054ef43035365a97a",
      volume: "1",
      unitValue: "kg",
      status: true,
      variant: "SOLID",
      __v: 0,
    },
    tax: {
      _id: "64a2c01254ef43035365a9a5",
      name: "GST",
      percentage: "18",
      status: true,
      __v: 0,
    },
    dailyNeed: {
      _id: "64a2f47b54ef43035365b1e0",
      name: "Rice & Rice Products",
      hindiName: "चावल एवं चावल उत्पाद",
      teluguName: "బియ్యం & బియ్యం ఉత్పత్తులు",
      bannerImg: "file-1688401019061-448292434.webp",
      location: {
        type: "Point",
        coordinates: [1.3654, 1.2658],
        _id: "64a2f47b54ef43035365b1e1",
      },
      deliveryTime: "01:00",
      openTime: [
        {
          startTime: "06:00",
          closeTime: "22:00",
          _id: "64a2f47b54ef43035365b1e2",
        },
      ],
      isActive: true,
      isChildren: true,
      __v: 0,
    },
    label: "product1",
    hindiLabel: "product1",
    teluguLabel: "product1",
    description: "product1",
    hindiDescription: "product1",
    TeluguDescription: "product1",
    isActive: true,
    productPriceInfo: [
      {
        size: "1",
        productUnit: {
          _id: "64a2be6054ef43035365a97a",
          volume: "1",
          unitValue: "kg",
          status: true,
          variant: "SOLID",
          __v: 0,
        },
        productPrice: "200",
        _id: "64a2fdb954ef43035365b3f1",
      },
      {
        size: "500",
        productUnit: {
          _id: "64a2fd6854ef43035365b3d8",
          volume: "1",
          unitValue: "GM",
          status: true,
          variant: "SOLID",
          __v: 0,
        },
        productPrice: "41",
        _id: "64a2fdb954ef43035365b3f2",
      },
    ],
    priceType: "ACTUAL",
    discountValue: "20",
    discountType: "PERCENTAGE",
    __v: 0,
  },
  {
    _id: "64a47e8654ef43035365c503",
    name: "Adff",
    hindiName: "Adff",
    teluguName: "Adff",
    img: "file-1688501894485-471830610.webp",
    type: "EGG",
    variants: "64a2be6054ef43035365a97a",
    availableStocks: "10",
    availableStockUnit: {
      _id: "64a2be6054ef43035365a97a",
      volume: "1",
      unitValue: "kg",
      status: true,
      variant: "SOLID",
      __v: 0,
    },
    tax: {
      _id: "64a2c01254ef43035365a9a5",
      name: "GST",
      percentage: "18",
      status: true,
      __v: 0,
    },
    dailyNeed: {
      _id: "64a2f47b54ef43035365b1e0",
      name: "Rice & Rice Products",
      hindiName: "चावल एवं चावल उत्पाद",
      teluguName: "బియ్యం & బియ్యం ఉత్పత్తులు",
      bannerImg: "file-1688401019061-448292434.webp",
      location: {
        type: "Point",
        coordinates: [1.3654, 1.2658],
        _id: "64a2f47b54ef43035365b1e1",
      },
      deliveryTime: "01:00",
      openTime: [
        {
          startTime: "06:00",
          closeTime: "22:00",
          _id: "64a2f47b54ef43035365b1e2",
        },
      ],
      isActive: true,
      isChildren: true,
      __v: 0,
    },
    label: "Adff",
    hindiLabel: "Adff",
    teluguLabel: "Adff",
    description: "Adff",
    hindiDescription: "Adff",
    TeluguDescription: "Adff",
    isActive: true,
    productPriceInfo: [
      {
        size: "1",
        productUnit: {
          _id: "64a2be6054ef43035365a97a",
          volume: "1",
          unitValue: "kg",
          status: true,
          variant: "SOLID",
          __v: 0,
        },
        productPrice: "120",
        _id: "64a47e8654ef43035365c504",
      },
      {
        size: "5",
        productUnit: {
          _id: "64a2be6054ef43035365a97a",
          volume: "1",
          unitValue: "kg",
          status: true,
          variant: "SOLID",
          __v: 0,
        },
        productPrice: "600",
        _id: "64a47e8654ef43035365c505",
      },
      {
        size: "10",
        productUnit: {
          _id: "64a2be6054ef43035365a97a",
          volume: "1",
          unitValue: "kg",
          status: true,
          variant: "SOLID",
          __v: 0,
        },
        productPrice: "1200",
        _id: "64a47e8654ef43035365c506",
      },
      {
        size: "11",
        productUnit: {
          _id: "64a2be6054ef43035365a97a",
          volume: "1",
          unitValue: "kg",
          status: true,
          variant: "SOLID",
          __v: 0,
        },
        productPrice: "1320",
        _id: "64a47e8654ef43035365c507",
      },
    ],
    priceType: "MRP",
    discountValue: "0",
    discountType: "RS",
    __v: 0,
  },
  {
    _id: "64a65bc754ef43035365db86",
    name: "KVR Brown Rice",
    hindiName: "KVR Brown Rice",
    teluguName: "KVR Brown Rice",
    img: "file-1688624071904-244534299.webp",
    type: "EGG",
    variants: "64a2be6054ef43035365a97a",
    availableStocks: "100",
    availableStockUnit: {
      _id: "64a2be6054ef43035365a97a",
      volume: "1",
      unitValue: "kg",
      status: true,
      variant: "SOLID",
      __v: 0,
    },
    tax: {
      _id: "64a2c01254ef43035365a9a5",
      name: "GST",
      percentage: "18",
      status: true,
      __v: 0,
    },
    dailyNeed: {
      _id: "64a2f47b54ef43035365b1e0",
      name: "Rice & Rice Products",
      hindiName: "चावल एवं चावल उत्पाद",
      teluguName: "బియ్యం & బియ్యం ఉత్పత్తులు",
      bannerImg: "file-1688401019061-448292434.webp",
      location: {
        type: "Point",
        coordinates: [1.3654, 1.2658],
        _id: "64a2f47b54ef43035365b1e1",
      },
      deliveryTime: "01:00",
      openTime: [
        {
          startTime: "06:00",
          closeTime: "22:00",
          _id: "64a2f47b54ef43035365b1e2",
        },
      ],
      isActive: true,
      isChildren: true,
      __v: 0,
    },
    label: "KVR Brown Rice",
    hindiLabel: "KVR Brown Rice",
    teluguLabel: "KVR Brown Rice",
    description: "KVR Brown Rice",
    hindiDescription: "KVR Brown Rice",
    TeluguDescription: "KVR Brown Rice",
    isActive: true,
    productPriceInfo: [
      {
        size: "1",
        productUnit: {
          _id: "64a2be6054ef43035365a97a",
          volume: "1",
          unitValue: "kg",
          status: true,
          variant: "SOLID",
          __v: 0,
        },
        productPrice: "120",
        _id: "64a65bc754ef43035365db87",
      },
    ],
    priceType: "MRP",
    discountValue: "0",
    discountType: "RS",
    __v: 0,
  },
  {
    _id: "64a723dd987da7c8464efab9",
    name: "12",
    hindiName: "1212",
    teluguName: "12",
    img: "file-1688675293484-361898512.webp",
    type: "VEG",
    variants: "64a2fd6854ef43035365b3d8",
    availableStocks: "12",
    availableStockUnit: {
      _id: "64a2fd6854ef43035365b3d8",
      volume: "1",
      unitValue: "GM",
      status: true,
      variant: "SOLID",
      __v: 0,
    },
    tax: {
      _id: "64a5560c54ef43035365d7c6",
      name: "kgst",
      percentage: "10",
      status: true,
      __v: 0,
    },
    dailyNeed: {
      _id: "64a2f47b54ef43035365b1e0",
      name: "Rice & Rice Products",
      hindiName: "चावल एवं चावल उत्पाद",
      teluguName: "బియ్యం & బియ్యం ఉత్పత్తులు",
      bannerImg: "file-1688401019061-448292434.webp",
      location: {
        type: "Point",
        coordinates: [1.3654, 1.2658],
        _id: "64a2f47b54ef43035365b1e1",
      },
      deliveryTime: "01:00",
      openTime: [
        {
          startTime: "06:00",
          closeTime: "22:00",
          _id: "64a2f47b54ef43035365b1e2",
        },
      ],
      isActive: true,
      isChildren: true,
      __v: 0,
    },
    label: "121",
    hindiLabel: "12",
    teluguLabel: "12",
    description: "12",
    hindiDescription: "12",
    TeluguDescription: "12",
    isActive: true,
    productPriceInfo: [
      {
        size: "12",
        productUnit: {
          _id: "64a2be6054ef43035365a97a",
          volume: "1",
          unitValue: "kg",
          status: true,
          variant: "SOLID",
          __v: 0,
        },
        productPrice: "12",
        _id: "64a723dd987da7c8464efaba",
      },
    ],
    priceType: "ACTUAL",
    discountValue: "23",
    discountType: "PERCENTAGE",
    __v: 0,
  },
  {
    _id: "64a72447987da7c8464efad1",
    name: "1",
    hindiName: "1",
    teluguName: "11",
    img: "file-1688675399105-648346793.webp",
    type: "NONVEG",
    variants: "64a2f15911ed82e3ded21d16",
    availableStocks: "10",
    availableStockUnit: {
      _id: "64a2f15911ed82e3ded21d16",
      volume: "1",
      unitValue: "Ltr",
      status: true,
      variant: "LIQUID",
      __v: 0,
    },
    tax: {
      _id: "64a5560c54ef43035365d7c6",
      name: "kgst",
      percentage: "10",
      status: true,
      __v: 0,
    },
    dailyNeed: {
      _id: "64a2f47b54ef43035365b1e0",
      name: "Rice & Rice Products",
      hindiName: "चावल एवं चावल उत्पाद",
      teluguName: "బియ్యం & బియ్యం ఉత్పత్తులు",
      bannerImg: "file-1688401019061-448292434.webp",
      location: {
        type: "Point",
        coordinates: [1.3654, 1.2658],
        _id: "64a2f47b54ef43035365b1e1",
      },
      deliveryTime: "01:00",
      openTime: [
        {
          startTime: "06:00",
          closeTime: "22:00",
          _id: "64a2f47b54ef43035365b1e2",
        },
      ],
      isActive: true,
      isChildren: true,
      __v: 0,
    },
    label: "1",
    hindiLabel: "1",
    teluguLabel: "1",
    description: "1",
    hindiDescription: "111",
    TeluguDescription: "1",
    isActive: true,
    productPriceInfo: [
      {
        size: "12",
        productUnit: {
          volume: "1",
          unitValue: "Ltr",
          status: true,
          variant: "LIQUID",
          _id: "64a2f15911ed82e3ded21d16",
          __v: 0,
        },
        productPrice: "21",
        _id: "64a72447987da7c8464efad2",
      },
      {
        size: "123",
        productUnit: {
          volume: "1",
          unitValue: "Ltr",
          status: true,
          variant: "LIQUID",
          _id: "64a2f15911ed82e3ded21d16",
          __v: 0,
        },
        productPrice: "20",
        _id: "64a72447987da7c8464efad3",
      },
    ],
    priceType: "ACTUAL",
    discountValue: "89",
    discountType: "PERCENTAGE",
    __v: 0,
  },
];

export const FoodAndBeveragesProductsData = [
  {
    _id: "64a2cfc554ef43035365ac68",
    name: "Egg Curry",
    hindiName: "अंडा करी",
    teluguName: "ఎగ్ కర్రీ",
    img: "file-1688390502248-378174798.webp",
    type: "VEG",
    variants: {
      _id: "64a2be6054ef43035365a97a",
      volume: "1",
      unitValue: "kg",
      status: true,
      variant: "SOLID",
      __v: 0,
    },
    availableStocks: "10",
    tax: "64a2c01254ef43035365a9a5",
    restaurantMenu: "64a2cfc454ef43035365ac5a",
    label: "Egg Curry",
    hindiLabel: "अंडा करी",
    teluguLabel: "ఎగ్ కర్రీ",
    description: "Egg Curry",
    hindiDescription: "अंडा करी",
    TeluguDescription: "ఎగ్ కర్రీ",
    isActive: true,
    productSize: "1",
    productUnit: {
      _id: "64a2be6054ef43035365a97a",
      volume: "1",
      unitValue: "kg",
      status: true,
      variant: "SOLID",
      __v: 0,
    },
    priceType: "MRP",
    productPrice: "170",
    discountValue: "25",
    discountType: "RS",
    __v: 0,
  },
  {
    _id: "64a2cfc554ef43035365ac69",
    name: "Egg Bhurji",
    hindiName: "एग भुर्जी",
    teluguName: "గుడ్డు బుర్జి",
    img: "file-1688390569141-478308286.webp",
    type: "VEG",
    variants: {
      _id: "64a2be6054ef43035365a97a",
      volume: "1",
      unitValue: "kg",
      status: true,
      variant: "SOLID",
      __v: 0,
    },
    availableStocks: "10",
    tax: "64a2c01254ef43035365a9a5",
    restaurantMenu: "64a2cfc454ef43035365ac5a",
    label: "Egg Bhurji",
    hindiLabel: "एग भुर्जी",
    teluguLabel: "గుడ్డు బుర్జి",
    description: "Egg Bhurji",
    hindiDescription: "एग भुर्जी",
    TeluguDescription: "గుడ్డు బుర్జి",
    isActive: true,
    productSize: "1",
    productUnit: {
      _id: "64a2be6054ef43035365a97a",
      volume: "1",
      unitValue: "kg",
      status: true,
      variant: "SOLID",
      __v: 0,
    },
    priceType: "MRP",
    productPrice: "220",
    discountValue: "0",
    discountType: "RS",
    __v: 0,
  },
];

export const ServiceProductsData = [
  {
    _id: "64a4530b54ef43035365bcd4",
    name: "Fan Repair",
    hindiName: "Fan Repair",
    teluguName: "Fan Repair",
    bannerImg: ["file-1688490405422-519068700.webp"],
    description: "Fan Repair",
    hindiDescription: "Fan Repair",
    teluguDescription: "Fan Repair",
    serviceType: "64a4530a54ef43035365bcbd",
    availableTime: [
      {
        startTime: "06:00",
        closeTime: "18:00",
        _id: "64a451a554ef43035365bc6c",
      },
    ],
    emergencyTime: [
      {
        startTime: "18:00",
        closeTime: "22:00",
        _id: "64a451a554ef43035365bc6d",
      },
    ],
    serviceCharge: 500,
    emergencyCharge: 1000,
    isActive: true,
    __v: 0,
  },
  {
    _id: "64a4530b54ef43035365bcd1",
    name: "Fan Installation",
    hindiName: "Fan Installation",
    teluguName: "Fan Installation",
    bannerImg: ["file-1688490363951-797617978.webp"],
    description: "Fan Installation",
    hindiDescription: "Fan Installation",
    teluguDescription: "Fan Installation",
    serviceType: "64a4530a54ef43035365bcbd",
    availableTime: [
      {
        startTime: "06:00",
        closeTime: "18:00",
        _id: "64a4517b54ef43035365bc67",
      },
    ],
    emergencyTime: [
      {
        startTime: "18:00",
        closeTime: "22:00",
        _id: "64a4517b54ef43035365bc68",
      },
    ],
    serviceCharge: 500,
    emergencyCharge: 1000,
    isActive: true,
    __v: 0,
  },
];